[package]
name = "ocpp_client"
version = "0.1.0"
edition = "2021"

[dependencies]
ocpp_core = { path = "../ocpp-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4.41", default-features = false, features = ["serde"] }
flume = "=0.10.12"
tokio = { version = "1", features = ["sync", "rt-multi-thread", "macros", "time"] }
tokio-util = "0.7.11"
futures = "0.3.31"
anyhow = "1.0"
async-trait = "0.1.88"
futures-util = "0.3"
uuid = { version = "1.8.0", features = ["v4"] }
log = "0.4"

[dev-dependencies]
chrono = { version = "0.4.41", default-features = false, features = ["serde", "now"] }
env_logger = "0.10"